export const CategoryConstant = {
  SPECIFICATION: 'SPECIFICATION',
  INFORMATION: 'INFORMATION',
  WARRANTY: 'WARRANTY',
  CERTIFICATION: 'CERTIFICATION',

  RATING_EQUAL_TO: 'EQUAL_TO',
  RATING_MORE_THAN: 'MORE_THAN',
  RATING_LESS_THAN: 'LESS_THAN',
  RATING_CONTAINS: 'CONTAINS',
  RATING_HAVE_VALUE: 'HAVE_VALUE',
};
