export const SequenceConstant = {
  PRODUCT_CATEGORY_PREFIX: 'CAT',
  PRODUCT_SUBCATEGORY_PREFIX: 'SCAT',
  PRODUCT_SPECIFICATION_PREFIX: 'SPEC',
  PRODUCT_SUBSPECIFICATION_PREFIX: 'SSPEC',
  PRODUCT_GENERAL_SPECIFICATION_PREFIX: 'GSPEC',
  PRODUCT_GENERAL_SUBSPECIFICATION_PREFIX: 'GSSPEC',
  PRODUCT_BASE_SPECIFICATION_PREFIX: 'BSPEC',
  PRODUCT_BASE_SUBSPECIFICATION_PREFIX: 'BSSPEC',
};
